const menuList = [
    {
        title:'home',
        key:'/home'
    },
    {
        title:'login',
        key:'/login'
    },
    {
        title:'assets',
        key:'/assets',
        children:[
            {
                title:'aws',
                key:'assets/aws'
            },
            {
                title:'aliyun',
                key:'aliyun'
            }
        ]
    },
    {
        title:'db',
        key:'/db',
        children:[
            {
                title:'mysql',
                key:'/db/mysql',
            },
            {
                title:'redis',
                key:'/db/redis',
            }
        ]
    },
    {
        title:'charts',
        key:'/charts',
        children:[
            {
                title:'bar',
                key:'/charts/bar'
            },
            {
                title:'pie',
                key:'/charts/pie'
            },
            {
                title:'line',
                key:'/charts/line'
            },
        ]
    },
    {
        title:'权限设置',
        key:'/permission'
    },
];
export default menuList;